function gameplay_pag(n) {
    var sp = document.getElementsByTagName("section");
    switch (n) {
        case 1: {
            sp[0].innerHTML = "<div id = 'gameplay'><h1> Giới thiệu về trò chơi bài Yugioh!</h1><p> Yu-Gi-Oh! thực chất là tên một bộ manga rất nổi tiếng của Nhật Bản xoay quanh thế giới các trò chơi, có tên gọi lần đầu khi phát hành ở Việt Nam là “ Vua trò chơi”. Phần lớn bộ truyện tập trung vào trò chơi hư cấu gọi là Duel Monster và trò chơi này đã được phát triển  Yu-Gi-Oh! Trading Card Game ở ngoài đời thực. </p><h3 align = 'center'> Những nhân vật chính trong bộ truyện</h3><div id = 'album'><div class = 'anh'><img src='image/yugi muto.jpg'/><b> Muto Yusei</b></div><div class = 'anh'><img src='image/jaden yuki.jpg'/><b> Jaden Yuki</b></div><div class = 'anh'><img src='image/fudu yusei.jpg'/><b> Fudu Yusei</b></div><div class = 'anh'><img src='image/tsukumo yuma.jpg'/><b> Tsukumo Yuma</b></div><div class = 'anh'><img src='image/yuya sakaki.png'/><b> Sakaki Yuya</b></div><div class = 'anh'><img src='image/fujiki yusaku.jpg'/><b> Fujiki Yusaku</b></div></div><p> Yu-Gi-Oh! (hay Yugioh) là một trò chơi đánh bài trong đó hai người chơi cố gắng đánh bại nhau bằng cách giảm Life Point ( Điểm sống) của đối thù về 0 bằng việc sử dụng các quân bài Quái vật, Phép thuật và Cạm bẫy.</p></div>";
            break;
        }
        case 2: {
            sp[0].innerHTML = "<div id = 'gameplay'><h1> Các vật dụng cần thiết để chơi</h1><p> Để có thể tiến hành trò chơi, bạn cần chuẩn bị  các vật dụng hỗ trợ cho trò chơi như sau:</p><ul class='ul'><li class='li'><b> Bộ bài chơi:</b> mỗi người chơi sẽ có một Bộ bài chơi riêng biệt. Cụ thể hơn hãy xem ở phần dưới.</li><li class='li'><b> Bàn chơi Yugioh:</b> nơi tiến hành đặt các quân bài và tổ chức trò chơi.</li><li class='li'><b> Một đồng xu:</b> một vài lá bài yêu cầu phải tung đồng xu.</li><li class='li'><b> Một quân xúc xắc:</b> một số lá bài yêu cầu phải tung xúc xắc.</li><li class='li'><b> Bộ đếm:</b> các vật nhỏ dùng để đánh dấu nhằm theo dõi những hiệu ứng ảnh hướng lên các lá bài.</li><li class='li'><b> Đại diện cho Quái vật (Monster Tokens):</b> sẽ được nhắc tới ở phần Luật khác.</li></ul><p> Ngoài ra, có một số vật dụng trợ giúp khác nhưng không bắt buộc như:</p><ul class='ul'><li class='li'><b> Máy tính:</b> Để theo dõi Life Point.</li><li class='li'><b> Bọc bài:</b> Để theo dõi Life Point.</li></ul></div>";
            break;
        }
        case 3: {
            sp[0].innerHTML = "<div id = 'gameplay'><h1> Bộ bài chơi Yugioh</h1><p> Mỗi người chơi trước khi chơi cần xây dựng ra 3 loại Bộ bài Yugioh để tiến hành chơi, bao gồm:</p><h3> 1. Main Deck: Bộ bài chính</h3><p> Là bộ bài mà người chơi sẽ tiến hành rút trong quá trình chơi. Bộ bài chính yêu cầu phải có từ 40 đến 60 quân bài. Thông thường để tăng tỉ lệ rút được bài, những người chơi chuyên nghiệp sẽ chỉ chơi với hơn 40 quân bài một chút. Trong một Bộ bài chính, bạn chỉ có thể cho tối đa 3 quân bài giống nhau vào. </p><h3> 2. Extra Deck: Bộ Bài  Bổ sung</h3><p> Là bộ bài là bộ bài chứa các lá bài thuộc loại Synchro và Fusion Monsters ( được giải thích ở phần dưới). Đây là những quân bài có thể được đưa vào chơi nếu đáp ứng một số điều kiện nhất định. Bộ bài này có thể có từ 0 đến 15 thẻ bài, và không tính vào số lượng của bộ Main Deck.</p><h3> 3. Side Deck: Bộ Bài bên ngoài</h3><p> Là một Bộ bài có từ 0 đến 15 thẻ bài, không được tính vào số lượng của bộ Main Deck. Là Bộ bài mà bạn dùng để điều chỉnh, thêm hay bớt vào Bộ bài chính giữa các hiệp đấu với một đối thủ. Người chơi có thể hoán đổi bất cứ thẻ nào từ Bộ bài ngoài này với Bộ bài Chính miễn đảm bảo số lượng tổng Bộ bài chính không thay đổi, đồng thời vẫn đảm bảo nguyên tắc: không có 3 quân bài cùng loại trong Bộ bài chính.</p></div>";
            break;
        }
        case 4: {
            sp[0].innerHTML = "<div id = 'gameplay'><h1> Các loại bài chơi Yugioh và cách đọc bài</h1><p> Thẻ bài chơi Yugioh được chia ra làm 3 loại chính:</p><h3> 1. Monster Cards : Loại bài Quái vật</h3><p> Các quân bài Quái vật trong Yugioh được chia thành các loại khác nhau:</p><p><b> Normal Monsters:</b> Quái vật thông thường.  Đây là các quân bài không có hiệu ứng đặc biệt nhưng thường có điểm ATK (sức mạnh) và DEF (phòng thủ) cao hơn Effect Monsters.</p><p><b> Effect Monsters:</b> Là các Quái vật có hiệu ứng đặc biệt, bên cạnh các chỉ số ATK và DEF cơ bản. Chúng bao gồm 5 loại khác nhau là:</p><p> Ngoài ra, còn có các loại bài Quái vật đặc biệt là Ritual, Fusion, và Synchro, Xyz, Pendulum, Link. Đây là các loại bài  muốn triệu hồi chúng để chơi cần phải hi sinh một số bài quái vật nào đó.</p><h3> Chi tiết một lá bài Quái vật như sau:</h3><center><img src = 'image/gameplay/monster.png'/></center><h3> 2. Spell Cards/ Bài Phép thuật và Trap Cards/Bài Cạm bẫy</h3><p> Sự khác biệt chính giữa bài Phép thuật và bài Cạm bẫy đó là bài Phép thuật thường được sử dụng để tăng cường khả năng tấn công trong khi đó bài Cạm bẫy thường để phá vỡ các cuộc tấn công của đối thủ. Ngoài ra, bài Bẫy phải được đặt ở trên bàn chơi mới sử dụng được và không được sử dụng cùng lúc trong cùng 1 lượt. Còn các bài phép thuật thì có thể sử dụng cùng lúc với nhau trong cùng 1 lượt chơi. </p><h3> Chi tiết một lá bài Phép thuật như sau:</h3><center><img src = 'image/gameplay/spell.png'/></center><h3> Chi tiết một lá bài Cạm bẫy  như sau:</h3><center><img src = 'image/gameplay/trap.png'/></center></div>";
            break;
        }
        case 5: {
            sp[0].innerHTML = "<div id = 'gameplay'><h1> Gameplay</h1><h3> Mục tiêu</h3><P> Mỗi trận đấu bài Yugioh sẽ trải qua 3 ván đấu. Người nào dành chiến thắng đa số   ván đấu ( thắng 3/3 hay ⅔ ) sẽ là người chiến thắng cuối cùng. </P><p> Mỗi ván đầu, mỗi người chơi sẽ bắt đầu với 8000 Life Point / Điểm sống. Người chơi chiến thắng dành chiến thắng một ván đấu nếu như:</p><ul><li> Trừ hết điểm Life Point của Đối thử về 0.</li><li> Tại thời điểm cần phải Rút bài, đối thủ của bạn không thể Rút được quân bài nào do hết bài rút.</li><li> Do kết quả của một lá bài nào đó mà bị xử thua.</li></ul><h3> Chuẩn bị trước khi chơi</h3><p> Người chơi cần tiến hành các bước cần thiết sau đây:</p><ul class='ul'><li class='li'> Xáo trộn Bộ bài Chính của mình cũng như của Đối thủ.</li><li class='li'> Đặt tất các các Bộ bài úp xuống khu vực của chúng trên Bàn chơi.</li><li class='li'>Người chơi đưa ra cho Đối thủ xem Bộ bài Bên ngoài của mình và đếm tất cả số lá bài trong mỗi bộ bài ( làm căn cứ để đảm bảo các bộ bài của các ván đấu là bằng nhau).</li><li class='li'>Nếu đây là ván đấu đầu tiên trong trận đấu, tiến hành trò chơi tung đồng xu hoặc kéo bua bao, để quyết định ai là người chơi đi trước. Nếu là các ván thứ 2, thứ 3, người thua cuộc của ván trước được quyền quyết định.</li><li class='li'>Mỗi người chơi tiến hành rút 5 lá bài từ bộ Bài chính và Bắt đầu ván chơi thôi nào!</li></ul><h3> Cách chơi một vàn bài Yugioh</h3><p> Yugioh là một trò chơi đánh bài theo lượt. Hai người chơi sẽ lần lượt tiến hành lượt chơi của mình cho đến khi có một người chơi dành chiến thắng. Mỗi lượt chơi được chia thành 6 Giai đoạn (Phase) theo thứ tự như sau:</p><p> 1. Draw Phase: Giai đoạn Rút bài</p><p> 2. Standby Phase: Giai đoạn Chờ</p><p> 3. Main Phase 1: Giai đoạn Chính 1 và Main Phase 2: Giai đoạn Chính 2</p><p> 4. Battle Phase:  Giai đoạn Chiến đấu</p><p> 6. End Phase: Giai đoạn Kết thúc</p></div>";
            break;
        }
        default: {
            sp[0].innerHTML = "<div id = 'gameplay'><h1> Các triệu hồi pháp</h1><p> Để sử dụng các lá bài Quái vật, bạn cần phải tiến hành Triệu hồi chúng ( hay còn gọi là Summoning Monsters ). Một số hành động Triệu hồi khá đơn giản, nhưng cũng có những hành động Triệu hồi phức tạp cần nhiều quân bài và nhiều bước. Các loại triệu hồi được phân như sau:</p><ul class='ul'><li class='li'><b> Triệu hồi Thông thường (Normal Summon):</b> Hầu hết Quái vật Thông thường (Normal Monsters) và các Quái vật có hiệu ứng (Effect Monsters) được triệu hồi theo cách này. Theo đó, bạn chỉ cần đơn giản là  đặt ngửa chúng trên bàn chơi, ở phần đặt dành cho Quái vật. </li><li class='li'><b> Triệu hồi Cống nạp (Tribute Summon):</b> Để triệu hồi các Quái vật có từ 5 sao trở lên bạn phải tiến hành Triệu hồi Cống nạp. Cống nạp được hiểu là việc đưa một quân bài quái vật đang chơi trên bàn vào Nghĩa đĩa, như một sự hy sinh. Với các Quái vật 5 và 6 sao, bạn phải hi sinh một Quái vật. Còn nếu nhiều hơn 7 sao, bạn phải hy sinh 2 Quái vật.</li><li class='li'><b> Triệu hồi lật bài (Flip Summon):</b> Khi bạn đặt úp  Quân bài Quái vật trên bàn chơi ở thế phòng thủ, quân bài này không được coi là đang được triệu hồi. Để thực sự triệu hồi những Quái vật này, bạn cần thực hiện Triệu hôi Lật bài. Một Quái vật khi được Triệu hồi Lật bài chỉ có thể chuyển sang trạng thái Tấn công, không được ở trạng thái phòng Thủ nhưng ngửa bài.  Bạn chỉ được phép chuyển sang phòng thủ ở lượt tiếp theo. </li><li class='li'><b>Triệu hồi đặc biệt (Special Summon ): </b>  Sử dụng để triệu hồi các Quái vật Đặc biệt đó là Synchro Summon, Fusion Summon, Ritual Summon, Xyz summon, Pendulum Summon, Link Summon</li></ul></div>";
        }
    }
}